### ISSUE TITLE
Autoupdates not working

### ISSUE THREAD

**Issue by seedprod** [WordPressDemo/WP-Demo#12]
Saw there is a new release but the it's not showing in the updates dashboard even after force recheck. Any ideas?

**Comment by dovy** [comment]
I'll get on that. Thought it was working. Boo.

**Comment by dovy** [comment]
Did you enter your updates key on the updates tab?  http://cl.ly/image/0h3S3G1l1O0t

**Comment by seedprod** [comment]
yep, it's enter on the main site.

**Comment by dovy** [comment]
Just resolved. The issue was a name mismatch. My bad. Thanks for that.
