### ISSUE TITLE
The Redux framework bundled with the plugin generates some issues

### ISSUE THREAD

**Issue by a4160939** [WordPressDemo/WP-Demo#15]
Well, this is kinda of strange. When I have both the plugin and my theme active, some fields inside the theme's settings render the old versions of the controls. My educated guess is that this is happening because the plugin loads an old version of the Redux framework (for the settings panel), and just because plugins load before the themes, my settings panel is picking the old functionality instead of the new one (the one that I bundled)

**Comment by a4160939** [comment]
I have updated the Redux framework inside the plugin and installed it again and all the strange issues are gone! So the question is, how can I ensure that my theme uses the Redux framework that I bundled inside?

**Comment by a4160939** [comment]
I found a better solution. Just installing the Redux plugin from the WordPress repository forces both plugins and themes to use an almost up-to-date version of the framework. Which is nice and solve the issues I was having before!

**Comment by dovy** [comment]
Indeed. That's how I built Redux to run.  ;)

I'll change WP-Demo to install the plugin instead to avoid those issues in the future. It will make the footprint smaller too.  ;)

**Comment by a4160939** [comment]
Awesome! Everyday I fall in love more and more with the framework. What a well-thought product! Keep it up!

**Comment by dovy** [comment]
Hah, thanks. It's my baby.  :)
