### ISSUE TITLE
parent_blog_id attribute does not work

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#16]
I'm using your shortcode as its documented here:
https://github.com/WordPressDemo/WP-Demo/wiki/Shortcodes#wp-demowp-demo---button-shortcode

```
[wp-demo parent_blog_id="4"][/wp-demo]
```

I then look into source to figure out why its not working and the attribute `parent_blog_id` isn't even available in the shortcode.

http://cl.ly/image/2k3G1h0I2B1b

Can this be available? I need to assign another site id as the demo template.

**Comment by bearded-avenger** [comment]
`submit_label` attribute also does not work

_edit_
this does work although i thought this was for the Launch Demo button text.

I was able to figure this out by including text within the shortcode, however the blog id feature doesnt seem to work.

**Comment by bearded-avenger** [comment]
just a friendly bump on this one . is this just a mistake in your documentation can the shortcode specify a blog id to clone?

**Comment by dovy** [comment]
Sorry, my kid is still in the hospital. I'll get back to you first of next week unless @bfintal is around.

**Comment by bfintal** [comment]
Fixed this, was a bit complex since each site has their own WP Demo settings.

**Comment by bfintal** [comment]
v1.0.8 that fixes this is now out :)
