### ISSUE TITLE
allow shortcodes to parse

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#17]
```
            function is_sandbox_shortcode( $atts, $content = null ) {
                if ( WPDemoSite::isGeneratedSite() ) {
                    return $content;
                }

                return '';
            }

```

This is causing this:
![image 2014-10-08 at 4 46 51 pm](https://cloud.githubusercontent.com/assets/1317303/4567832/d69bcd42-4f34-11e4-961e-e89e08e05f9d.png)

Can you please update to accommodate?

echo do_shortcode($content);

**Comment by dovy** [comment]
So sorry. @bfintal can you make this change?

My newborn baby just went into the hospital again. I am out of commission for at least this week. Sorry.

**Comment by bearded-avenger** [comment]
sorry to hear guys. :(

i edited my copy to allow this so I'm good on this one, not a rush. this however I was hoping for a fix on if at all possible:
https://github.com/WordPressDemo/WP-Demo/issues/16

**Comment by bfintal** [comment]
Applied in all `return $content` instances in `class-shortcode.php`

**Comment by bfintal** [comment]
v1.0.8 that fixes this is now out :)

**Comment by bearded-avenger** [comment]
Much appreciated!
