### ISSUE TITLE
Media Not Moved

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#18]
When a new demo site is created from the parent site the images in the cloned site are all 404. The images in the uploads directory are not moved with the cloned site.

**Comment by dovy** [comment]
Good call. @bfintal this should be an easy fix.

**Comment by bearded-avenger** [comment]
really appreciate it!

**Comment by bfintal** [comment]
Easy fix? I dunno what you mean by this, haha! :p

**Comment by dovy** [comment]
Haha. I meant to leave the url rewrites, but you're right. Not easy.

**Comment by bearded-avenger** [comment]
Thanks Guys. Out of all the issues I've created this one is the show stopper for the time being.

**Comment by bfintal** [comment]
Hi there, I'm afraid I'm going to need more information regarding this. I tested this and the contents of the `uploads` folder get copied. Even those just manually placed inside the `uploads` folder are getting copied over to the new site.

**Comment by bearded-avenger** [comment]
http://tryaesop.com

You can test and see for yourself here. The images are not being moved.

**Comment by bfintal** [comment]
Okay found something.

When I upload an image in my tests, I get this. This is an image in my **test** site:

```
http://wputmu/test/wp-content/uploads/sites/2/2014/10/image.jpg
```

After I create a demo, my new site gets this. I see this file when viewing WP's media manager. This is from my new **bbbcdb91aa743a2ab28c6b0e** site:

```
http://wputmu/bbbcdb91aa743a2ab28c6b0e/wp-content/uploads/sites/10/2014/10/image.jpg
```

In your case, WP's media manager is showing these types of URLs:

```
http://tryaesop.com/1992a6e4cfdd51d5acdc5f18/files/2014/10/logo.jpg
```

What's the `files` folder? This won't be copied since it's not the `uploads` folder of WP. Or am I missing something?

**Comment by bearded-avenger** [comment]
To be honest I've no idea. This is a standard run-of-the-mill multisite install on Lightning Base. No modifications at all. Other plugins, like Blog Copier, Duplicator, all work with moving the media.

I'll ping the host.

**Comment by bearded-avenger** [comment]
Spotted this in .htaccess . 

```
# uploaded files
RewriteRule ^([_0-9a-zA-Z-]+/)?files/(.+) wp-includes/ms-files.php?file=$2 [L]
```

This is however correct because its a subfolder multisite setup? Does WP Demo support a directory setup? I'll update this once I hear from LB.

**Comment by bfintal** [comment]
Yup, we recommend subfolders in multisite.

Can you check if files in the `wp-content/uploads/sites/xx` are actually copied?

**Comment by bearded-avenger** [comment]
this was indeed a bug on the hosts end. works now. thanks guys.

**Comment by bfintal** [comment]
Glad it worked out! What was the issue?

**Comment by bearded-avenger** [comment]
Yep so some Host installers are still installing wp ms in the old way with running uploads through ms-files.php. New MS installs aren't done like this anymore. They had to partially rebuild my install and will fix the auto installer through cpanel.
