### ISSUE TITLE
does this plugin supports multisite(subdomain)?

### ISSUE THREAD

**Issue by pjyong** [WordPressDemo/WP-Demo#22]
Hello, 
I have two questions for you.
1. does this plugin supports multisite(subdomain)?
2. I have one main site, that's my company site, like "abc.com", now I have one demo site, "demo.abc.com", does this plugin create sandbox from "demo.abc.com", not from main site?
Thanks
June

**Comment by dovy** [comment]
Indeed. It's based off of multi-site and each multi-site instance can have a demo attached to it. :)
