### ISSUE TITLE
Edit Available Demo Functions?

### ISSUE THREAD

**Issue by thatryan** [WordPressDemo/WP-Demo#6]
Can you choose what is available in the demo site? Example, can users of the demo be allowed to edit options in the theme customizer or a framework (such as redux) to see how their site would like styled up?

**Comment by dovy** [comment]
WordPress Demo ships with a Demo User role that includes the editor rights with Theme Options, so they can edit a theme or plugin. If you want more, you can download User Role Editor to modify permissions.  :)

Let me know if you have any other questions.

**Comment by thatryan** [comment]
OK cool, I guess the demo I tried out did not have that option to edit any text/colors ect. I just tried the cabana demo though and it does. 

So, to clarify, I can create a set of options with Redux that the user can edit to "set up the site" how they would want it in the sandbox, and they also have the ability to export the settings if they wish so that we can then implement their "design"?

Thank you :)

**Comment by dovy** [comment]
I just signed in under Cabana, and have this as what I can see: http://cl.ly/image/2u3u3D0G2w0O   At the bottom left is the Cabana options panel where they can modify their own themes.

To clarify, you create a role of any kind using User Role Editor. WP-Demo ships with a "Demo User" role which is the editor role + manage options.

Redux is embedded and they very much could setup things how they want and export them, but there's no requirement for them to do so.
