### ISSUE TITLE
Hide Mandrill Dashboard Widget

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#8]
Hey fellas,
Great job with this plugin, works wonderfully. I setup Mandrill as suggested, however, when the user logs in, the dashboard widget and menu items are visible to them.

http://cl.ly/image/0B1c173c0C3I

This isn't so much a bug report, but more of a request, to hide this widget from users if wpmandrill is active.

Thanks!

**Comment by dovy** [comment]
Glad you like it! The easiest solution for that is to install User Role Editor and altering their rights there.

However, I can add that code in. It's a good idea.  :)

Give me until early next week.  ;)

**Comment by bearded-avenger** [comment]
Awesome!

**Comment by dovy** [comment]
Implemented in 1.0.5 just released.
