### ISSUE TITLE
Filter Requests

### ISSUE THREAD

**Issue by bearded-avenger** [WordPressDemo/WP-Demo#9]
hey hey!
Can I request a few filters? There's some text I'd like to change.

class-email.php line 79 - "A sandbox activation email will be sent to the email address."
class-shortcode.php line 246 - "Please provide the following information."

Thanks!!

**Comment by dovy** [comment]
Not a prob. We'll get on it first of next week.

**Comment by dovy** [comment]
Will have in 1.0.5 every string being able to be filtered.  ;)   Hope to release tonight.

**Comment by dovy** [comment]
Here are the new filters coming out with 1.0.5: https://github.com/WordPressDemo/WP-Demo/wiki/Filters
